// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

/**
 * @param {string} content
 * @returns {Promise<void> & { cancel(): void }}
 */
export function CopyItemContent(content) {
    let $resultPromise = /** @type {any} */($Call.ByID(989603669, content));
    return $resultPromise;
}

/**
 * @param {string} name
 * @returns {Promise<string> & { cancel(): void }}
 */
export function GetClipData(name) {
    let $resultPromise = /** @type {any} */($Call.ByID(1512325848, name));
    return $resultPromise;
}

/**
 * @param {string} name
 * @returns {Promise<string> & { cancel(): void }}
 */
export function Greet(name) {
    let $resultPromise = /** @type {any} */($Call.ByID(3460737983, name));
    return $resultPromise;
}

/**
 * just a wrapper to have access to App functions
 * not necessary if you don't plan to do anything with your App on shortcut use
 * @returns {Promise<void> & { cancel(): void }}
 */
export function RegisterHotKey() {
    let $resultPromise = /** @type {any} */($Call.ByID(3452269361));
    return $resultPromise;
}
