// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyItemContent(arg1:string):Promise<void>;

export function GetClipData(arg1:string):Promise<string>;

export function RegisterHotKey():Promise<void>;
