// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyItemContent(arg1) {
  return window['go']['main']['App']['CopyItemContent'](arg1);
}

export function GetClipData(arg1) {
  return window['go']['main']['App']['GetClipData'](arg1);
}

export function RegisterHotKey() {
  return window['go']['main']['App']['RegisterHotKey']();
}
